import Sidebar from "@/components/sidebar.main";
import Head from "next/head";
import Image from "next/image";
import styles_navbar from "@/styles/Navbar.module.scss";
import styles from "@/styles/Home.module.scss";
import { InputText } from "primereact/inputtext";
import { Avatar } from "primereact/avatar";
import { Menu } from "primereact/menu";
import { useRef } from "react";
import ActiveUser from "@/components/ActiveUser";
import NewUser from "@/components/NewUser";
import RepeatUser from "@/components/RepeatUser";
import TotalRevenue from "@/components/TotalRevenue";
import TopStories from "@/components/TopStories";
import RecentActivity from "@/components/RecentActivity";

export default function Home() {
  const menuLeft = useRef(null);

  const items = [
    {
      label: "Profile",
    },
    {
      label: "Logout",
    },
  ];
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.page}>
        {/* sidebar */}
        <div>
          <Sidebar />
        </div>
        {/* right section */}
        <div className={styles.right_panel}>
          {/* navbar */}
          <div className={styles_navbar.navbar}>
            <span className="p-input-icon-left">
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M21 21L16.514 16.506M19 10.5C19 12.7543 18.1045 14.9163 16.5104 16.5104C14.9163 18.1045 12.7543 19 10.5 19C8.24566 19 6.08365 18.1045 4.48959 16.5104C2.89553 14.9163 2 12.7543 2 10.5C2 8.24566 2.89553 6.08365 4.48959 4.48959C6.08365 2.89553 8.24566 2 10.5 2C12.7543 2 14.9163 2.89553 16.5104 4.48959C18.1045 6.08365 19 8.24566 19 10.5V10.5Z"
                  stroke="#CECECE"
                  stroke-width="2"
                  stroke-linecap="round"
                />
              </svg>
              <InputText placeholder="Search" />
            </span>
            <div className={styles_navbar.navbar_right}>
              <section className={styles_navbar.calender}>
                <span>11-10-2022</span>
                <span>OR</span>
                <span>11-10-2022</span>
              </section>
              <Menu model={items} popup ref={menuLeft} id="popup_menu_left" />

              <section
                onClick={(event) => menuLeft.current.toggle(event)}
                className={styles_navbar.welcome_container}
              >
                <section className={styles_navbar.welcome_container_left}>
                  <Avatar name="kinsghuk Sarkar" />
                  <section>
                    <p>Welcome back,</p>
                    <h3>Akshita Patel</h3>
                  </section>
                </section>
                <section>
                  <svg
                    width="16"
                    height="10"
                    viewBox="0 0 16 10"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M0.46967 0.96967C0.735936 0.703403 1.1526 0.679197 1.44621 0.897052L1.53033 0.96967L8 7.439L14.4697 0.96967C14.7359 0.703403 15.1526 0.679197 15.4462 0.897052L15.5303 0.96967C15.7966 1.23594 15.8208 1.6526 15.6029 1.94621L15.5303 2.03033L8.53033 9.03033C8.26406 9.2966 7.8474 9.3208 7.55379 9.10295L7.46967 9.03033L0.46967 2.03033C0.176777 1.73744 0.176777 1.26256 0.46967 0.96967Z"
                      fill="#1E2875"
                    />
                  </svg>
                </section>
              </section>
            </div>
          </div>
          {/* welcome container */}
          <div className={styles.welcome_container}>
            <h1>Welcome Back , Akshita</h1>
            <p>Here is today&apos;s report and performence</p>
          </div>
          {/* status log */}
          <div className={styles.status}>
            <ActiveUser />
            <NewUser />
            <RepeatUser />
            <TotalRevenue />
          </div>
          {/* charts */}
          <div className={styles.chart}></div>
          {/* payment and subscription */}
          <div className={styles.chart}></div>
          {/* activity */}
          <div className={styles.activity}>
            <TopStories />
            <RecentActivity />
          </div>
        </div>
      </main>
    </>
  );
}
